version: "3.7"
networks:
  xxl:
    external: true
services:
  mongo:
    image: mongo:latest
    networks:
      - xxl
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/config:/data/configdb:rw
      - ./mongo/db:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=civic
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
