version: "3.7"
networks:
  xxl:
    external: true
services:
  mysql:
    image: mysql:latest
    networks:
      - xxl
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=civic
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]