version: "3.7"
networks:
  xxl:
    external: true
services:
  nginx:
    image: nginx:latest
    networks:
      - xxl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/dist:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role== manager