version: "3.7"
networks:
  xxl:
    external: true
services:
  portainer:
    image: portainer/portainer:latest
    networks:
      - xxl
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]