version: "3.7"
networks:
  xxl:
    external: true
services:
  redis:
    image: redis:latest
    networks:
      - xxl
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
      - ./redis:/data:rw
    command: redis-server /etc/redis/redis.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager